<?php

/**
 * Author: Kavin Thakkar
 * Date: 3/1/22
 * File: base_plus_commission_employee.class.php
 * Description: The base_plus_commission_employee.class.php contains the class named
 * BasePlusCommissionEmployee, which inherits from the CommissionEmployee class.
 */
class BasePlusCommissionEmployee extends CommissionEmployee
{
    private $base_salary;

    public function __construct($name, $title, $years, $salary) {
        parent::__construct($name, $title, $years, $salary);
    }

    public function getBaseSalary() {
        return $this->base_salary;
    }

    public function getPaymentAmount() {
        return parent::getPaymentAmount(); // TODO: Change the autogenerated stub
    }

    public function toString() {
        //echo it up!
    }
}